version: "3.7"
services:
  app:
    build: .
    container_name: api
    image: node_app
    ports:
      - 8888:8888
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - app-network
  db:
    container_name: db
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=tao
    networks:
      - app-network
    # extra_hosts:
    #   - "dockerhost:127.0.0.1"
networks:
  app-network:
    driver: bridge
